# Build without the GUI (egui/wgpu) front end:  rpmbuild --without gui
# The TUI, SMI and JSON modes are always built.
%bcond_without gui

# Upstream's [profile.release] sets `strip = true`, so the binary carries no
# debug information and an extracted debuginfo package would have an empty file
# list (which is a hard build failure).
%global debug_package %{nil}

%global forgeurl    https://github.com/Umio-Yasuno/amdgpu_top
%global appid       io.github.umio_yasuno.amdgpu_top
%global baserelease 1

%if %{with gui}
%global cargo_features libdrm_link,tui,gui,json
%else
%global cargo_features libdrm_link,tui,json
%endif

# Not defined on older EL releases.
%{!?_metainfodir:%global _metainfodir %{_datadir}/metainfo}

Name:           amdgpu_top
Version:        0.11.5
# `gitsnapshot` is defined by .copr/Makefile for builds off a non-release commit.
Release:        %{baserelease}%{?gitsnapshot:.%{gitsnapshot}}%{?dist}
Summary:        Tool to display AMDGPU usage

%if %{with gui}
# The GUI embeds the BIZ UDGothic font, which is OFL-1.1.
License:        MIT AND OFL-1.1
%else
License:        MIT
%endif
URL:            %{forgeurl}

Source0:        %{forgeurl}/archive/v%{version}/%{name}-%{version}.tar.gz
# Generated by rpm/make-vendor-tarball.sh; see rpm/README.md.  Holds vendor/ and
# the .cargo/config.toml that points crates.io *and* the libdrm_amdgpu_sys git
# dependency at it, so the build needs no network access.
Source1:        %{name}-%{version}-vendor.tar.zst

%if %{defined rust_arches}
ExclusiveArch:  %{rust_arches}
%else
ExclusiveArch:  x86_64 aarch64
%endif

%if 0%{?rhel}
# On RHEL/EPEL rustc and cargo come from rust-toolset.  amdgpu_top is Rust
# edition 2024, so the toolset must provide rust >= 1.85.
BuildRequires:  rust-toolset
%else
BuildRequires:  cargo
BuildRequires:  rust >= 1.85
%endif
BuildRequires:  gcc
# To unpack Source1.
BuildRequires:  zstd
BuildRequires:  desktop-file-utils
# libdrm_amdgpu_sys is built with its `link_drm` feature, i.e. it links against
# -ldrm -ldrm_amdgpu rather than dlopen()ing them.  Its `buildtime_bindgen`
# feature stays off, so no clang/bindgen is needed.
BuildRequires:  pkgconfig(libdrm)
%if 0%{?fedora}
BuildRequires:  libappstream-glib
%endif

%description
amdgpu_top displays AMD GPU utilization, similar to umr, radeontop or
intel_gpu_top.  It reports information gathered from the GPU performance
counters (GRBM, GRBM2), sensors, fdinfo, gpu_metrics and the amdgpu kernel
driver.

It offers a TUI mode (the default), an SMI mode (--smi), a JSON output mode
(--json)%{?with_gui:, a GUI mode (--gui)} and a one-shot device dump (-d).

%prep
%autosetup -n %{name}-%{version}
# Unpacks vendor/ and .cargo/config.toml into the source tree.
tar -xf %{SOURCE1}

%build
%if %{defined build_rustflags}
export RUSTFLAGS="%{build_rustflags}"
%endif
export CARGO_NET_OFFLINE=true

cargo build \
    --release \
    --offline \
    --locked \
    %{?_smp_build_ncpus:-j%{_smp_build_ncpus}} \
    --no-default-features \
    --features=%{cargo_features}

%install
install -Dpm0755 target/release/%{name} %{buildroot}%{_bindir}/%{name}
install -Dpm0644 docs/%{name}.1 %{buildroot}%{_mandir}/man1/%{name}.1
install -Dpm0644 assets/%{name}-tui.desktop \
    %{buildroot}%{_datadir}/applications/%{name}-tui.desktop
install -Dpm0644 assets/%{appid}.metainfo.xml \
    %{buildroot}%{_metainfodir}/%{appid}.metainfo.xml
%if %{with gui}
install -Dpm0644 assets/%{name}.desktop \
    %{buildroot}%{_datadir}/applications/%{name}.desktop
%endif

%check
desktop-file-validate %{buildroot}%{_datadir}/applications/*.desktop
%if 0%{?fedora}
appstream-util validate-relax --nonet \
    %{buildroot}%{_metainfodir}/%{appid}.metainfo.xml
%endif

%files
%license LICENSE
%if %{with gui}
%license crates/amdgpu_top_gui/fonts/LICENSE_BIZUDGothic
%endif
%doc README.md CHANGELOG.md AUTHORS
%{_bindir}/%{name}
%{_mandir}/man1/%{name}.1*
%{_datadir}/applications/%{name}-tui.desktop
%{_metainfodir}/%{appid}.metainfo.xml
%if %{with gui}
%{_datadir}/applications/%{name}.desktop
%endif

%changelog
* Sun Aug 09 2026 clemperorpenguin <clem@pendragon.systems> - 0.11.5-1
- Initial package
