#!/usr/bin/env bash
#
# Build the vendored-crates tarball that rpm/amdgpu_top.spec expects as Source1.
#
# amdgpu_top depends on libdrm_amdgpu_sys by git revision, so the crates cannot
# be unbundled into individual Fedora rust-* packages.  Instead every dependency
# is vendored ahead of time and the build runs with --offline, which is what
# lets it work in mock/copr where the build chroot has no network access.
#
# Usage: make-vendor-tarball.sh <source-tarball> [output-dir]
#
#   <source-tarball>  amdgpu_top-X.Y.Z.tar.gz, e.g. the GitHub release archive
#                     or one produced by `git archive`.  Its top-level directory
#                     name determines the output file name.
#   [output-dir]      Where to write the tarball.  Default: current directory.
#
# Produces <name>-<version>-vendor.tar.zst containing:
#   vendor/               the vendored crate sources
#   .cargo/config.toml    source replacement, generated by `cargo vendor`
#
# Requires network access (it downloads the crates) plus cargo, git, tar, zstd.

set -euo pipefail

if [[ $# -lt 1 || $# -gt 2 ]]; then
    sed -n '/^# Usage:/,/^# Requires/p' "$0" >&2
    exit 2
fi

src_tarball=$(readlink -f "$1")
outdir=$(readlink -f "${2:-$PWD}")

[[ -f $src_tarball ]] || { echo "no such file: $src_tarball" >&2; exit 1; }
mkdir -p "$outdir"

# The unpacked vendor tree is around 720 MB, which does not fit in a small /tmp
# tmpfs, so scratch space goes next to the output by default.  Override with
# VENDOR_TMPDIR.
workdir=$(mktemp -d "${VENDOR_TMPDIR:-$outdir}/vendor-build.XXXXXXXX")
trap 'rm -rf "$workdir"' EXIT

tar -xf "$src_tarball" -C "$workdir"

# The tarball holds a single top-level directory named "<name>-<version>".
shopt -s nullglob
srcdirs=("$workdir"/*)
if [[ ${#srcdirs[@]} -ne 1 || ! -d ${srcdirs[0]} ]]; then
    echo "expected exactly one top-level directory in $src_tarball" >&2
    exit 1
fi
srcdir_name=$(basename "${srcdirs[0]}")
out_tarball="$outdir/${srcdir_name}-vendor.tar.zst"

cd "${srcdirs[0]}"

mkdir -p .cargo
# `cargo vendor` writes the crate sources into vendor/ and prints the matching
# source-replacement stanzas (crates.io plus the libdrm_amdgpu_sys git source)
# on stdout.
cargo vendor --locked vendor > .cargo/config.toml

# --sort=name and fixed ownership keep the tarball reproducible.
#
# The vendor directory is ~720 MB, and zstd's higher levels need a lot of memory
# per thread; level 15 keeps the peak modest on small builders while giving up
# only a few percent of ratio.  Raise it on a roomier machine with
# ZSTD_LEVEL=19.
tar --sort=name \
    --owner=0 --group=0 --numeric-owner \
    --mtime="@${SOURCE_DATE_EPOCH:-0}" \
    -cf - vendor .cargo \
    | zstd "-${ZSTD_LEVEL:-15}" -T0 -q -o "$out_tarball" -f

echo "$out_tarball"
